// Code generated by Fern. DO NOT EDIT.

package client

import (
	account "sdk/account"
	commodities "sdk/commodities"
	core "sdk/core"
	crypto "sdk/crypto"
	currencies "sdk/currencies"
	indices "sdk/indices"
	internal "sdk/internal"
	option "sdk/option"
	stocks "sdk/stocks"
)

type Client struct {
	Account     *account.Client
	Currencies  *currencies.Client
	Crypto      *crypto.Client
	Indices     *indices.Client
	Stocks      *stocks.Client
	Commodities *commodities.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Account:     account.NewClient(options),
		Currencies:  currencies.NewClient(options),
		Crypto:      crypto.NewClient(options),
		Indices:     indices.NewClient(options),
		Stocks:      stocks.NewClient(options),
		Commodities: commodities.NewClient(options),
		options:     options,
		baseURL:     options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
