/*
tradewatch.io

Testing CommoditiesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package tradewatch

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/tradewatch-io/go-sdk"
)

func Test_tradewatch_CommoditiesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CommoditiesAPIService getQuote", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var symbol string

		resp, httpRes, err := apiClient.CommoditiesAPI.getQuote(context.Background(), symbol).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CommoditiesAPIService getSymbols", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CommoditiesAPI.getSymbols(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CommoditiesAPIService getTypes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CommoditiesAPI.getTypes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
