/*
tradewatch.io

Testing CurrenciesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package tradewatch

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/tradewatch-io/go-sdk"
)

func Test_tradewatch_CurrenciesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CurrenciesAPIService convert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var from string
		var to string

		resp, httpRes, err := apiClient.CurrenciesAPI.convert(context.Background(), from, to).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CurrenciesAPIService getQuote", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var symbol string

		resp, httpRes, err := apiClient.CurrenciesAPI.getQuote(context.Background(), symbol).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CurrenciesAPIService getSymbols", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CurrenciesAPI.getSymbols(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
