// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCommoditiesGetInsightsRequest(t *testing.T) {
	t.Run("SetCursor", func(t *testing.T) {
		obj := &CommoditiesGetInsightsRequest{}
		var fernTestValueCursor *string
		obj.SetCursor(fernTestValueCursor)
		assert.Equal(t, fernTestValueCursor, obj.Cursor)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSize", func(t *testing.T) {
		obj := &CommoditiesGetInsightsRequest{}
		var fernTestValueSize *int
		obj.SetSize(fernTestValueSize)
		assert.Equal(t, fernTestValueSize, obj.Size)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCommoditiesGetInsightsRequest(t *testing.T) {
	t.Run("SetCursor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetInsightsRequest{}
		var fernTestValueCursor *string

		// Act
		obj.SetCursor(fernTestValueCursor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetInsightsRequest{}
		var fernTestValueSize *int

		// Act
		obj.SetSize(fernTestValueSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCommoditiesGetQuoteRequest(t *testing.T) {
	t.Run("SetSymbol", func(t *testing.T) {
		obj := &CommoditiesGetQuoteRequest{}
		var fernTestValueSymbol string
		obj.SetSymbol(fernTestValueSymbol)
		assert.Equal(t, fernTestValueSymbol, obj.Symbol)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPrecision", func(t *testing.T) {
		obj := &CommoditiesGetQuoteRequest{}
		var fernTestValuePrecision *int
		obj.SetPrecision(fernTestValuePrecision)
		assert.Equal(t, fernTestValuePrecision, obj.Precision)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCommoditiesGetQuoteRequest(t *testing.T) {
	t.Run("SetSymbol_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetQuoteRequest{}
		var fernTestValueSymbol string

		// Act
		obj.SetSymbol(fernTestValueSymbol)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPrecision_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetQuoteRequest{}
		var fernTestValuePrecision *int

		// Act
		obj.SetPrecision(fernTestValuePrecision)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCommoditiesGetQuotesRequest(t *testing.T) {
	t.Run("SetSymbols", func(t *testing.T) {
		obj := &CommoditiesGetQuotesRequest{}
		var fernTestValueSymbols string
		obj.SetSymbols(fernTestValueSymbols)
		assert.Equal(t, fernTestValueSymbols, obj.Symbols)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPrecision", func(t *testing.T) {
		obj := &CommoditiesGetQuotesRequest{}
		var fernTestValuePrecision *int
		obj.SetPrecision(fernTestValuePrecision)
		assert.Equal(t, fernTestValuePrecision, obj.Precision)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCommoditiesGetQuotesRequest(t *testing.T) {
	t.Run("SetSymbols_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetQuotesRequest{}
		var fernTestValueSymbols string

		// Act
		obj.SetSymbols(fernTestValueSymbols)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPrecision_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetQuotesRequest{}
		var fernTestValuePrecision *int

		// Act
		obj.SetPrecision(fernTestValuePrecision)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCommoditiesGetSymbolsRequest(t *testing.T) {
	t.Run("SetSize", func(t *testing.T) {
		obj := &CommoditiesGetSymbolsRequest{}
		var fernTestValueSize *int
		obj.SetSize(fernTestValueSize)
		assert.Equal(t, fernTestValueSize, obj.Size)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMode", func(t *testing.T) {
		obj := &CommoditiesGetSymbolsRequest{}
		var fernTestValueMode *string
		obj.SetMode(fernTestValueMode)
		assert.Equal(t, fernTestValueMode, obj.Mode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetType", func(t *testing.T) {
		obj := &CommoditiesGetSymbolsRequest{}
		var fernTestValueType *string
		obj.SetType(fernTestValueType)
		assert.Equal(t, fernTestValueType, obj.Type)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCountry", func(t *testing.T) {
		obj := &CommoditiesGetSymbolsRequest{}
		var fernTestValueCountry *string
		obj.SetCountry(fernTestValueCountry)
		assert.Equal(t, fernTestValueCountry, obj.Country)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCursor", func(t *testing.T) {
		obj := &CommoditiesGetSymbolsRequest{}
		var fernTestValueCursor *string
		obj.SetCursor(fernTestValueCursor)
		assert.Equal(t, fernTestValueCursor, obj.Cursor)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCommoditiesGetSymbolsRequest(t *testing.T) {
	t.Run("SetSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetSymbolsRequest{}
		var fernTestValueSize *int

		// Act
		obj.SetSize(fernTestValueSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetSymbolsRequest{}
		var fernTestValueMode *string

		// Act
		obj.SetMode(fernTestValueMode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetSymbolsRequest{}
		var fernTestValueType *string

		// Act
		obj.SetType(fernTestValueType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCountry_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetSymbolsRequest{}
		var fernTestValueCountry *string

		// Act
		obj.SetCountry(fernTestValueCountry)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCursor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommoditiesGetSymbolsRequest{}
		var fernTestValueCursor *string

		// Act
		obj.SetCursor(fernTestValueCursor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCommodityTypeObj(t *testing.T) {
	t.Run("SetSymbol", func(t *testing.T) {
		obj := &CommodityTypeObj{}
		var fernTestValueSymbol string
		obj.SetSymbol(fernTestValueSymbol)
		assert.Equal(t, fernTestValueSymbol, obj.Symbol)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCommodityTypeObj(t *testing.T) {
	t.Run("GetSymbol", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommodityTypeObj{}
		var expected string
		obj.Symbol = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSymbol(), "getter should return the property value")
	})

	t.Run("GetSymbol_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CommodityTypeObj
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSymbol() // Should return zero value
	})

}

func TestSettersMarkExplicitCommodityTypeObj(t *testing.T) {
	t.Run("SetSymbol_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommodityTypeObj{}
		var fernTestValueSymbol string

		// Act
		obj.SetSymbol(fernTestValueSymbol)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCommodityTypesList(t *testing.T) {
	t.Run("SetItems", func(t *testing.T) {
		obj := &CommodityTypesList{}
		var fernTestValueItems []*CommodityTypeObj
		obj.SetItems(fernTestValueItems)
		assert.Equal(t, fernTestValueItems, obj.Items)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCommodityTypesList(t *testing.T) {
	t.Run("GetItems", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommodityTypesList{}
		var expected []*CommodityTypeObj
		obj.Items = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetItems(), "getter should return the property value")
	})

	t.Run("GetItems_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommodityTypesList{}
		obj.Items = nil

		// Act & Assert
		assert.Nil(t, obj.GetItems(), "getter should return nil when property is nil")
	})

	t.Run("GetItems_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CommodityTypesList
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetItems() // Should return zero value
	})

}

func TestSettersMarkExplicitCommodityTypesList(t *testing.T) {
	t.Run("SetItems_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommodityTypesList{}
		var fernTestValueItems []*CommodityTypeObj

		// Act
		obj.SetItems(fernTestValueItems)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCommodityTypeObj(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommodityTypeObj{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CommodityTypeObj
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CommodityTypeObj
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CommodityTypeObj
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCommodityTypesList(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CommodityTypesList{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CommodityTypesList
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CommodityTypesList
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CommodityTypesList
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCommodityTypeObj(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CommodityTypeObj{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CommodityTypeObj
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCommodityTypesList(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CommodityTypesList{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CommodityTypesList
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesCommodityTypeObj(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CommodityTypeObj{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CommodityTypeObj
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCommodityTypesList(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CommodityTypesList{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CommodityTypesList
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
