// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

var (
	commoditiesGetInsightsRequestFieldCursor = big.NewInt(1 << 0)
	commoditiesGetInsightsRequestFieldSize   = big.NewInt(1 << 1)
)

type CommoditiesGetInsightsRequest struct {
	// Cursor for the next page
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// The number of items per page.
	Size *int `json:"-" url:"size,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CommoditiesGetInsightsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetInsightsRequest) SetCursor(cursor *string) {
	c.Cursor = cursor
	c.require(commoditiesGetInsightsRequestFieldCursor)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetInsightsRequest) SetSize(size *int) {
	c.Size = size
	c.require(commoditiesGetInsightsRequestFieldSize)
}

var (
	commoditiesGetQuoteRequestFieldSymbol    = big.NewInt(1 << 0)
	commoditiesGetQuoteRequestFieldPrecision = big.NewInt(1 << 1)
)

type CommoditiesGetQuoteRequest struct {
	// The symbol to get the quote for.
	Symbol string `json:"-" url:"symbol"`
	// The decimal precision of the result.
	Precision *int `json:"-" url:"precision,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CommoditiesGetQuoteRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSymbol sets the Symbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetQuoteRequest) SetSymbol(symbol string) {
	c.Symbol = symbol
	c.require(commoditiesGetQuoteRequestFieldSymbol)
}

// SetPrecision sets the Precision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetQuoteRequest) SetPrecision(precision *int) {
	c.Precision = precision
	c.require(commoditiesGetQuoteRequestFieldPrecision)
}

var (
	commoditiesGetQuotesRequestFieldSymbols   = big.NewInt(1 << 0)
	commoditiesGetQuotesRequestFieldPrecision = big.NewInt(1 << 1)
)

type CommoditiesGetQuotesRequest struct {
	// Comma separated list of symbols.
	Symbols string `json:"-" url:"symbols"`
	// The decimal precision of the result.
	Precision *int `json:"-" url:"precision,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CommoditiesGetQuotesRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSymbols sets the Symbols field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetQuotesRequest) SetSymbols(symbols string) {
	c.Symbols = symbols
	c.require(commoditiesGetQuotesRequestFieldSymbols)
}

// SetPrecision sets the Precision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetQuotesRequest) SetPrecision(precision *int) {
	c.Precision = precision
	c.require(commoditiesGetQuotesRequestFieldPrecision)
}

var (
	commoditiesGetSymbolsRequestFieldSize    = big.NewInt(1 << 0)
	commoditiesGetSymbolsRequestFieldMode    = big.NewInt(1 << 1)
	commoditiesGetSymbolsRequestFieldType    = big.NewInt(1 << 2)
	commoditiesGetSymbolsRequestFieldCountry = big.NewInt(1 << 3)
	commoditiesGetSymbolsRequestFieldCursor  = big.NewInt(1 << 4)
)

type CommoditiesGetSymbolsRequest struct {
	// The number of items per page.
	Size *int `json:"-" url:"size,omitempty"`
	// The mode of the response.
	Mode *string `json:"-" url:"mode,omitempty"`
	// Type of the instrument.
	Type *string `json:"-" url:"type,omitempty"`
	// Country of the instrument.
	Country *string `json:"-" url:"country,omitempty"`
	// Cursor for the next page
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CommoditiesGetSymbolsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetSymbolsRequest) SetSize(size *int) {
	c.Size = size
	c.require(commoditiesGetSymbolsRequestFieldSize)
}

// SetMode sets the Mode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetSymbolsRequest) SetMode(mode *string) {
	c.Mode = mode
	c.require(commoditiesGetSymbolsRequestFieldMode)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetSymbolsRequest) SetType(type_ *string) {
	c.Type = type_
	c.require(commoditiesGetSymbolsRequestFieldType)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetSymbolsRequest) SetCountry(country *string) {
	c.Country = country
	c.require(commoditiesGetSymbolsRequestFieldCountry)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommoditiesGetSymbolsRequest) SetCursor(cursor *string) {
	c.Cursor = cursor
	c.require(commoditiesGetSymbolsRequestFieldCursor)
}

var (
	commodityTypeObjFieldSymbol = big.NewInt(1 << 0)
)

type CommodityTypeObj struct {
	// Commodity type name
	Symbol string `json:"symbol" url:"symbol"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CommodityTypeObj) GetSymbol() string {
	if c == nil {
		return ""
	}
	return c.Symbol
}

func (c *CommodityTypeObj) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CommodityTypeObj) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSymbol sets the Symbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommodityTypeObj) SetSymbol(symbol string) {
	c.Symbol = symbol
	c.require(commodityTypeObjFieldSymbol)
}

func (c *CommodityTypeObj) UnmarshalJSON(data []byte) error {
	type unmarshaler CommodityTypeObj
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CommodityTypeObj(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CommodityTypeObj) MarshalJSON() ([]byte, error) {
	type embed CommodityTypeObj
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CommodityTypeObj) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// A list of commodity types
var (
	commodityTypesListFieldItems = big.NewInt(1 << 0)
)

type CommodityTypesList struct {
	Items []*CommodityTypeObj `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CommodityTypesList) GetItems() []*CommodityTypeObj {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CommodityTypesList) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CommodityTypesList) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommodityTypesList) SetItems(items []*CommodityTypeObj) {
	c.Items = items
	c.require(commodityTypesListFieldItems)
}

func (c *CommodityTypesList) UnmarshalJSON(data []byte) error {
	type unmarshaler CommodityTypesList
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CommodityTypesList(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CommodityTypesList) MarshalJSON() ([]byte, error) {
	type embed CommodityTypesList
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CommodityTypesList) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
