// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

var (
	cryptoConvertRequestFieldFrom      = big.NewInt(1 << 0)
	cryptoConvertRequestFieldTo        = big.NewInt(1 << 1)
	cryptoConvertRequestFieldAmount    = big.NewInt(1 << 2)
	cryptoConvertRequestFieldPrecision = big.NewInt(1 << 3)
)

type CryptoConvertRequest struct {
	// The symbol you want to convert from.
	From string `json:"-" url:"-"`
	// The symbol you want to convert to.
	To string `json:"-" url:"-"`
	// The amount to be converted.
	Amount *float64 `json:"-" url:"amount,omitempty"`
	// The decimal precision of the result.
	Precision *int `json:"-" url:"precision,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptoConvertRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConvertRequest) SetFrom(from string) {
	c.From = from
	c.require(cryptoConvertRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConvertRequest) SetTo(to string) {
	c.To = to
	c.require(cryptoConvertRequestFieldTo)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConvertRequest) SetAmount(amount *float64) {
	c.Amount = amount
	c.require(cryptoConvertRequestFieldAmount)
}

// SetPrecision sets the Precision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConvertRequest) SetPrecision(precision *int) {
	c.Precision = precision
	c.require(cryptoConvertRequestFieldPrecision)
}

var (
	cryptoGetInsightsRequestFieldCursor = big.NewInt(1 << 0)
	cryptoGetInsightsRequestFieldSize   = big.NewInt(1 << 1)
)

type CryptoGetInsightsRequest struct {
	// Cursor for the next page
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// The number of items per page.
	Size *int `json:"-" url:"size,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptoGetInsightsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetInsightsRequest) SetCursor(cursor *string) {
	c.Cursor = cursor
	c.require(cryptoGetInsightsRequestFieldCursor)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetInsightsRequest) SetSize(size *int) {
	c.Size = size
	c.require(cryptoGetInsightsRequestFieldSize)
}

var (
	cryptoGetQuoteRequestFieldSymbol    = big.NewInt(1 << 0)
	cryptoGetQuoteRequestFieldPrecision = big.NewInt(1 << 1)
)

type CryptoGetQuoteRequest struct {
	// The symbol to get the quote for.
	Symbol string `json:"-" url:"symbol"`
	// The decimal precision of the result.
	Precision *int `json:"-" url:"precision,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptoGetQuoteRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSymbol sets the Symbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetQuoteRequest) SetSymbol(symbol string) {
	c.Symbol = symbol
	c.require(cryptoGetQuoteRequestFieldSymbol)
}

// SetPrecision sets the Precision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetQuoteRequest) SetPrecision(precision *int) {
	c.Precision = precision
	c.require(cryptoGetQuoteRequestFieldPrecision)
}

var (
	cryptoGetQuotesRequestFieldSymbols   = big.NewInt(1 << 0)
	cryptoGetQuotesRequestFieldPrecision = big.NewInt(1 << 1)
)

type CryptoGetQuotesRequest struct {
	// Comma separated list of symbols.
	Symbols string `json:"-" url:"symbols"`
	// The decimal precision of the result.
	Precision *int `json:"-" url:"precision,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptoGetQuotesRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSymbols sets the Symbols field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetQuotesRequest) SetSymbols(symbols string) {
	c.Symbols = symbols
	c.require(cryptoGetQuotesRequestFieldSymbols)
}

// SetPrecision sets the Precision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetQuotesRequest) SetPrecision(precision *int) {
	c.Precision = precision
	c.require(cryptoGetQuotesRequestFieldPrecision)
}

var (
	cryptoGetSymbolsRequestFieldSize    = big.NewInt(1 << 0)
	cryptoGetSymbolsRequestFieldMode    = big.NewInt(1 << 1)
	cryptoGetSymbolsRequestFieldType    = big.NewInt(1 << 2)
	cryptoGetSymbolsRequestFieldCountry = big.NewInt(1 << 3)
	cryptoGetSymbolsRequestFieldCursor  = big.NewInt(1 << 4)
)

type CryptoGetSymbolsRequest struct {
	// The number of items per page.
	Size *int `json:"-" url:"size,omitempty"`
	// The mode of the response.
	Mode *string `json:"-" url:"mode,omitempty"`
	// Type of the instrument.
	Type *string `json:"-" url:"type,omitempty"`
	// Country of the instrument.
	Country *string `json:"-" url:"country,omitempty"`
	// Cursor for the next page
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CryptoGetSymbolsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetSymbolsRequest) SetSize(size *int) {
	c.Size = size
	c.require(cryptoGetSymbolsRequestFieldSize)
}

// SetMode sets the Mode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetSymbolsRequest) SetMode(mode *string) {
	c.Mode = mode
	c.require(cryptoGetSymbolsRequestFieldMode)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetSymbolsRequest) SetType(type_ *string) {
	c.Type = type_
	c.require(cryptoGetSymbolsRequestFieldType)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetSymbolsRequest) SetCountry(country *string) {
	c.Country = country
	c.require(cryptoGetSymbolsRequestFieldCountry)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoGetSymbolsRequest) SetCursor(cursor *string) {
	c.Cursor = cursor
	c.require(cryptoGetSymbolsRequestFieldCursor)
}

var (
	cryptoConversionFieldInfo   = big.NewInt(1 << 0)
	cryptoConversionFieldQuery  = big.NewInt(1 << 1)
	cryptoConversionFieldResult = big.NewInt(1 << 2)
)

type CryptoConversion struct {
	Info   *ConversionInfo        `json:"info" url:"info"`
	Query  *CryptoConversionQuery `json:"query" url:"query"`
	Result float64                `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptoConversion) GetInfo() *ConversionInfo {
	if c == nil {
		return nil
	}
	return c.Info
}

func (c *CryptoConversion) GetQuery() *CryptoConversionQuery {
	if c == nil {
		return nil
	}
	return c.Query
}

func (c *CryptoConversion) GetResult() float64 {
	if c == nil {
		return 0
	}
	return c.Result
}

func (c *CryptoConversion) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptoConversion) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetInfo sets the Info field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConversion) SetInfo(info *ConversionInfo) {
	c.Info = info
	c.require(cryptoConversionFieldInfo)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConversion) SetQuery(query *CryptoConversionQuery) {
	c.Query = query
	c.require(cryptoConversionFieldQuery)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConversion) SetResult(result float64) {
	c.Result = result
	c.require(cryptoConversionFieldResult)
}

func (c *CryptoConversion) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptoConversion
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptoConversion(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptoConversion) MarshalJSON() ([]byte, error) {
	type embed CryptoConversion
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptoConversion) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptoConversionQueryFieldFrom      = big.NewInt(1 << 0)
	cryptoConversionQueryFieldTo        = big.NewInt(1 << 1)
	cryptoConversionQueryFieldAmount    = big.NewInt(1 << 2)
	cryptoConversionQueryFieldPrecision = big.NewInt(1 << 3)
)

type CryptoConversionQuery struct {
	// The symbol you want to convert from.
	From string `json:"from" url:"from"`
	// The symbol you want to convert to.
	To string `json:"to" url:"to"`
	// The amount to be converted.
	Amount *float64 `json:"amount,omitempty" url:"amount,omitempty"`
	// The decimal precision of the result.
	Precision *int `json:"precision,omitempty" url:"precision,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptoConversionQuery) GetFrom() string {
	if c == nil {
		return ""
	}
	return c.From
}

func (c *CryptoConversionQuery) GetTo() string {
	if c == nil {
		return ""
	}
	return c.To
}

func (c *CryptoConversionQuery) GetAmount() *float64 {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CryptoConversionQuery) GetPrecision() *int {
	if c == nil {
		return nil
	}
	return c.Precision
}

func (c *CryptoConversionQuery) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptoConversionQuery) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConversionQuery) SetFrom(from string) {
	c.From = from
	c.require(cryptoConversionQueryFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConversionQuery) SetTo(to string) {
	c.To = to
	c.require(cryptoConversionQueryFieldTo)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConversionQuery) SetAmount(amount *float64) {
	c.Amount = amount
	c.require(cryptoConversionQueryFieldAmount)
}

// SetPrecision sets the Precision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoConversionQuery) SetPrecision(precision *int) {
	c.Precision = precision
	c.require(cryptoConversionQueryFieldPrecision)
}

func (c *CryptoConversionQuery) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptoConversionQuery
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptoConversionQuery(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptoConversionQuery) MarshalJSON() ([]byte, error) {
	type embed CryptoConversionQuery
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptoConversionQuery) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// A cryptocurrency exchange
var (
	cryptoExchangeItemFieldID              = big.NewInt(1 << 0)
	cryptoExchangeItemFieldName            = big.NewInt(1 << 1)
	cryptoExchangeItemFieldYearEstablished = big.NewInt(1 << 2)
	cryptoExchangeItemFieldCountry         = big.NewInt(1 << 3)
	cryptoExchangeItemFieldWebsite         = big.NewInt(1 << 4)
)

type CryptoExchangeItem struct {
	// Exchange identifier (e.g. binance, coinbase-pro).
	ID string `json:"id" url:"id"`
	// Exchange name (e.g. Binance, Coinbase Pro).
	Name string `json:"name" url:"name"`
	// The year the exchange was established
	YearEstablished *int `json:"year_established,omitempty" url:"year_established,omitempty"`
	// The country where the exchange is based.
	Country *string `json:"country,omitempty" url:"country,omitempty"`
	// The exchange's official website URL.
	Website string `json:"website" url:"website"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptoExchangeItem) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CryptoExchangeItem) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CryptoExchangeItem) GetYearEstablished() *int {
	if c == nil {
		return nil
	}
	return c.YearEstablished
}

func (c *CryptoExchangeItem) GetCountry() *string {
	if c == nil {
		return nil
	}
	return c.Country
}

func (c *CryptoExchangeItem) GetWebsite() string {
	if c == nil {
		return ""
	}
	return c.Website
}

func (c *CryptoExchangeItem) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptoExchangeItem) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoExchangeItem) SetID(id string) {
	c.ID = id
	c.require(cryptoExchangeItemFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoExchangeItem) SetName(name string) {
	c.Name = name
	c.require(cryptoExchangeItemFieldName)
}

// SetYearEstablished sets the YearEstablished field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoExchangeItem) SetYearEstablished(yearEstablished *int) {
	c.YearEstablished = yearEstablished
	c.require(cryptoExchangeItemFieldYearEstablished)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoExchangeItem) SetCountry(country *string) {
	c.Country = country
	c.require(cryptoExchangeItemFieldCountry)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoExchangeItem) SetWebsite(website string) {
	c.Website = website
	c.require(cryptoExchangeItemFieldWebsite)
}

func (c *CryptoExchangeItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptoExchangeItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptoExchangeItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptoExchangeItem) MarshalJSON() ([]byte, error) {
	type embed CryptoExchangeItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptoExchangeItem) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// A list of cryptocurrency exchanges
var (
	cryptoExchangesListFieldItems = big.NewInt(1 << 0)
)

type CryptoExchangesList struct {
	Items []*CryptoExchangeItem `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptoExchangesList) GetItems() []*CryptoExchangeItem {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CryptoExchangesList) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptoExchangesList) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoExchangesList) SetItems(items []*CryptoExchangeItem) {
	c.Items = items
	c.require(cryptoExchangesListFieldItems)
}

func (c *CryptoExchangesList) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptoExchangesList
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptoExchangesList(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptoExchangesList) MarshalJSON() ([]byte, error) {
	type embed CryptoExchangesList
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptoExchangesList) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
