// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCryptoConvertRequest(t *testing.T) {
	t.Run("SetFrom", func(t *testing.T) {
		obj := &CryptoConvertRequest{}
		var fernTestValueFrom string
		obj.SetFrom(fernTestValueFrom)
		assert.Equal(t, fernTestValueFrom, obj.From)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTo", func(t *testing.T) {
		obj := &CryptoConvertRequest{}
		var fernTestValueTo string
		obj.SetTo(fernTestValueTo)
		assert.Equal(t, fernTestValueTo, obj.To)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAmount", func(t *testing.T) {
		obj := &CryptoConvertRequest{}
		var fernTestValueAmount *float64
		obj.SetAmount(fernTestValueAmount)
		assert.Equal(t, fernTestValueAmount, obj.Amount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPrecision", func(t *testing.T) {
		obj := &CryptoConvertRequest{}
		var fernTestValuePrecision *int
		obj.SetPrecision(fernTestValuePrecision)
		assert.Equal(t, fernTestValuePrecision, obj.Precision)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCryptoConvertRequest(t *testing.T) {
	t.Run("SetFrom_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConvertRequest{}
		var fernTestValueFrom string

		// Act
		obj.SetFrom(fernTestValueFrom)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConvertRequest{}
		var fernTestValueTo string

		// Act
		obj.SetTo(fernTestValueTo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAmount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConvertRequest{}
		var fernTestValueAmount *float64

		// Act
		obj.SetAmount(fernTestValueAmount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPrecision_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConvertRequest{}
		var fernTestValuePrecision *int

		// Act
		obj.SetPrecision(fernTestValuePrecision)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCryptoGetInsightsRequest(t *testing.T) {
	t.Run("SetCursor", func(t *testing.T) {
		obj := &CryptoGetInsightsRequest{}
		var fernTestValueCursor *string
		obj.SetCursor(fernTestValueCursor)
		assert.Equal(t, fernTestValueCursor, obj.Cursor)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSize", func(t *testing.T) {
		obj := &CryptoGetInsightsRequest{}
		var fernTestValueSize *int
		obj.SetSize(fernTestValueSize)
		assert.Equal(t, fernTestValueSize, obj.Size)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCryptoGetInsightsRequest(t *testing.T) {
	t.Run("SetCursor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetInsightsRequest{}
		var fernTestValueCursor *string

		// Act
		obj.SetCursor(fernTestValueCursor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetInsightsRequest{}
		var fernTestValueSize *int

		// Act
		obj.SetSize(fernTestValueSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCryptoGetQuoteRequest(t *testing.T) {
	t.Run("SetSymbol", func(t *testing.T) {
		obj := &CryptoGetQuoteRequest{}
		var fernTestValueSymbol string
		obj.SetSymbol(fernTestValueSymbol)
		assert.Equal(t, fernTestValueSymbol, obj.Symbol)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPrecision", func(t *testing.T) {
		obj := &CryptoGetQuoteRequest{}
		var fernTestValuePrecision *int
		obj.SetPrecision(fernTestValuePrecision)
		assert.Equal(t, fernTestValuePrecision, obj.Precision)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCryptoGetQuoteRequest(t *testing.T) {
	t.Run("SetSymbol_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetQuoteRequest{}
		var fernTestValueSymbol string

		// Act
		obj.SetSymbol(fernTestValueSymbol)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPrecision_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetQuoteRequest{}
		var fernTestValuePrecision *int

		// Act
		obj.SetPrecision(fernTestValuePrecision)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCryptoGetQuotesRequest(t *testing.T) {
	t.Run("SetSymbols", func(t *testing.T) {
		obj := &CryptoGetQuotesRequest{}
		var fernTestValueSymbols string
		obj.SetSymbols(fernTestValueSymbols)
		assert.Equal(t, fernTestValueSymbols, obj.Symbols)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPrecision", func(t *testing.T) {
		obj := &CryptoGetQuotesRequest{}
		var fernTestValuePrecision *int
		obj.SetPrecision(fernTestValuePrecision)
		assert.Equal(t, fernTestValuePrecision, obj.Precision)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCryptoGetQuotesRequest(t *testing.T) {
	t.Run("SetSymbols_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetQuotesRequest{}
		var fernTestValueSymbols string

		// Act
		obj.SetSymbols(fernTestValueSymbols)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPrecision_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetQuotesRequest{}
		var fernTestValuePrecision *int

		// Act
		obj.SetPrecision(fernTestValuePrecision)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCryptoGetSymbolsRequest(t *testing.T) {
	t.Run("SetSize", func(t *testing.T) {
		obj := &CryptoGetSymbolsRequest{}
		var fernTestValueSize *int
		obj.SetSize(fernTestValueSize)
		assert.Equal(t, fernTestValueSize, obj.Size)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMode", func(t *testing.T) {
		obj := &CryptoGetSymbolsRequest{}
		var fernTestValueMode *string
		obj.SetMode(fernTestValueMode)
		assert.Equal(t, fernTestValueMode, obj.Mode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetType", func(t *testing.T) {
		obj := &CryptoGetSymbolsRequest{}
		var fernTestValueType *string
		obj.SetType(fernTestValueType)
		assert.Equal(t, fernTestValueType, obj.Type)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCountry", func(t *testing.T) {
		obj := &CryptoGetSymbolsRequest{}
		var fernTestValueCountry *string
		obj.SetCountry(fernTestValueCountry)
		assert.Equal(t, fernTestValueCountry, obj.Country)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCursor", func(t *testing.T) {
		obj := &CryptoGetSymbolsRequest{}
		var fernTestValueCursor *string
		obj.SetCursor(fernTestValueCursor)
		assert.Equal(t, fernTestValueCursor, obj.Cursor)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCryptoGetSymbolsRequest(t *testing.T) {
	t.Run("SetSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetSymbolsRequest{}
		var fernTestValueSize *int

		// Act
		obj.SetSize(fernTestValueSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetSymbolsRequest{}
		var fernTestValueMode *string

		// Act
		obj.SetMode(fernTestValueMode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetSymbolsRequest{}
		var fernTestValueType *string

		// Act
		obj.SetType(fernTestValueType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCountry_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetSymbolsRequest{}
		var fernTestValueCountry *string

		// Act
		obj.SetCountry(fernTestValueCountry)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCursor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoGetSymbolsRequest{}
		var fernTestValueCursor *string

		// Act
		obj.SetCursor(fernTestValueCursor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCryptoConversion(t *testing.T) {
	t.Run("SetInfo", func(t *testing.T) {
		obj := &CryptoConversion{}
		var fernTestValueInfo *ConversionInfo
		obj.SetInfo(fernTestValueInfo)
		assert.Equal(t, fernTestValueInfo, obj.Info)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQuery", func(t *testing.T) {
		obj := &CryptoConversion{}
		var fernTestValueQuery *CryptoConversionQuery
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResult", func(t *testing.T) {
		obj := &CryptoConversion{}
		var fernTestValueResult float64
		obj.SetResult(fernTestValueResult)
		assert.Equal(t, fernTestValueResult, obj.Result)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCryptoConversion(t *testing.T) {
	t.Run("GetInfo", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversion{}
		var expected *ConversionInfo
		obj.Info = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetInfo(), "getter should return the property value")
	})

	t.Run("GetInfo_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversion{}
		obj.Info = nil

		// Act & Assert
		assert.Nil(t, obj.GetInfo(), "getter should return nil when property is nil")
	})

	t.Run("GetInfo_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversion
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetInfo() // Should return zero value
	})

	t.Run("GetQuery", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversion{}
		var expected *CryptoConversionQuery
		obj.Query = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetQuery(), "getter should return the property value")
	})

	t.Run("GetQuery_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversion{}
		obj.Query = nil

		// Act & Assert
		assert.Nil(t, obj.GetQuery(), "getter should return nil when property is nil")
	})

	t.Run("GetQuery_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversion
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetQuery() // Should return zero value
	})

	t.Run("GetResult", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversion{}
		var expected float64
		obj.Result = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResult(), "getter should return the property value")
	})

	t.Run("GetResult_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversion
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResult() // Should return zero value
	})

}

func TestSettersMarkExplicitCryptoConversion(t *testing.T) {
	t.Run("SetInfo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversion{}
		var fernTestValueInfo *ConversionInfo

		// Act
		obj.SetInfo(fernTestValueInfo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversion{}
		var fernTestValueQuery *CryptoConversionQuery

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResult_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversion{}
		var fernTestValueResult float64

		// Act
		obj.SetResult(fernTestValueResult)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCryptoConversionQuery(t *testing.T) {
	t.Run("SetFrom", func(t *testing.T) {
		obj := &CryptoConversionQuery{}
		var fernTestValueFrom string
		obj.SetFrom(fernTestValueFrom)
		assert.Equal(t, fernTestValueFrom, obj.From)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTo", func(t *testing.T) {
		obj := &CryptoConversionQuery{}
		var fernTestValueTo string
		obj.SetTo(fernTestValueTo)
		assert.Equal(t, fernTestValueTo, obj.To)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAmount", func(t *testing.T) {
		obj := &CryptoConversionQuery{}
		var fernTestValueAmount *float64
		obj.SetAmount(fernTestValueAmount)
		assert.Equal(t, fernTestValueAmount, obj.Amount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPrecision", func(t *testing.T) {
		obj := &CryptoConversionQuery{}
		var fernTestValuePrecision *int
		obj.SetPrecision(fernTestValuePrecision)
		assert.Equal(t, fernTestValuePrecision, obj.Precision)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCryptoConversionQuery(t *testing.T) {
	t.Run("GetFrom", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}
		var expected string
		obj.From = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFrom(), "getter should return the property value")
	})

	t.Run("GetFrom_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversionQuery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFrom() // Should return zero value
	})

	t.Run("GetTo", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}
		var expected string
		obj.To = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTo(), "getter should return the property value")
	})

	t.Run("GetTo_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversionQuery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTo() // Should return zero value
	})

	t.Run("GetAmount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}
		var expected *float64
		obj.Amount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAmount(), "getter should return the property value")
	})

	t.Run("GetAmount_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}
		obj.Amount = nil

		// Act & Assert
		assert.Nil(t, obj.GetAmount(), "getter should return nil when property is nil")
	})

	t.Run("GetAmount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversionQuery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAmount() // Should return zero value
	})

	t.Run("GetPrecision", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}
		var expected *int
		obj.Precision = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPrecision(), "getter should return the property value")
	})

	t.Run("GetPrecision_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}
		obj.Precision = nil

		// Act & Assert
		assert.Nil(t, obj.GetPrecision(), "getter should return nil when property is nil")
	})

	t.Run("GetPrecision_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversionQuery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPrecision() // Should return zero value
	})

}

func TestSettersMarkExplicitCryptoConversionQuery(t *testing.T) {
	t.Run("SetFrom_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}
		var fernTestValueFrom string

		// Act
		obj.SetFrom(fernTestValueFrom)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}
		var fernTestValueTo string

		// Act
		obj.SetTo(fernTestValueTo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAmount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}
		var fernTestValueAmount *float64

		// Act
		obj.SetAmount(fernTestValueAmount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPrecision_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}
		var fernTestValuePrecision *int

		// Act
		obj.SetPrecision(fernTestValuePrecision)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCryptoExchangeItem(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &CryptoExchangeItem{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &CryptoExchangeItem{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetYearEstablished", func(t *testing.T) {
		obj := &CryptoExchangeItem{}
		var fernTestValueYearEstablished *int
		obj.SetYearEstablished(fernTestValueYearEstablished)
		assert.Equal(t, fernTestValueYearEstablished, obj.YearEstablished)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCountry", func(t *testing.T) {
		obj := &CryptoExchangeItem{}
		var fernTestValueCountry *string
		obj.SetCountry(fernTestValueCountry)
		assert.Equal(t, fernTestValueCountry, obj.Country)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWebsite", func(t *testing.T) {
		obj := &CryptoExchangeItem{}
		var fernTestValueWebsite string
		obj.SetWebsite(fernTestValueWebsite)
		assert.Equal(t, fernTestValueWebsite, obj.Website)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCryptoExchangeItem(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoExchangeItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		var expected string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoExchangeItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetYearEstablished", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		var expected *int
		obj.YearEstablished = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetYearEstablished(), "getter should return the property value")
	})

	t.Run("GetYearEstablished_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		obj.YearEstablished = nil

		// Act & Assert
		assert.Nil(t, obj.GetYearEstablished(), "getter should return nil when property is nil")
	})

	t.Run("GetYearEstablished_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoExchangeItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetYearEstablished() // Should return zero value
	})

	t.Run("GetCountry", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		var expected *string
		obj.Country = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCountry(), "getter should return the property value")
	})

	t.Run("GetCountry_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		obj.Country = nil

		// Act & Assert
		assert.Nil(t, obj.GetCountry(), "getter should return nil when property is nil")
	})

	t.Run("GetCountry_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoExchangeItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCountry() // Should return zero value
	})

	t.Run("GetWebsite", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		var expected string
		obj.Website = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWebsite(), "getter should return the property value")
	})

	t.Run("GetWebsite_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoExchangeItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWebsite() // Should return zero value
	})

}

func TestSettersMarkExplicitCryptoExchangeItem(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetYearEstablished_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		var fernTestValueYearEstablished *int

		// Act
		obj.SetYearEstablished(fernTestValueYearEstablished)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCountry_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		var fernTestValueCountry *string

		// Act
		obj.SetCountry(fernTestValueCountry)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWebsite_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}
		var fernTestValueWebsite string

		// Act
		obj.SetWebsite(fernTestValueWebsite)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCryptoExchangesList(t *testing.T) {
	t.Run("SetItems", func(t *testing.T) {
		obj := &CryptoExchangesList{}
		var fernTestValueItems []*CryptoExchangeItem
		obj.SetItems(fernTestValueItems)
		assert.Equal(t, fernTestValueItems, obj.Items)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCryptoExchangesList(t *testing.T) {
	t.Run("GetItems", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangesList{}
		var expected []*CryptoExchangeItem
		obj.Items = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetItems(), "getter should return the property value")
	})

	t.Run("GetItems_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangesList{}
		obj.Items = nil

		// Act & Assert
		assert.Nil(t, obj.GetItems(), "getter should return nil when property is nil")
	})

	t.Run("GetItems_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoExchangesList
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetItems() // Should return zero value
	})

}

func TestSettersMarkExplicitCryptoExchangesList(t *testing.T) {
	t.Run("SetItems_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangesList{}
		var fernTestValueItems []*CryptoExchangeItem

		// Act
		obj.SetItems(fernTestValueItems)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCryptoConversion(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversion{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CryptoConversion
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CryptoConversion
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CryptoConversion
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCryptoConversionQuery(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoConversionQuery{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CryptoConversionQuery
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CryptoConversionQuery
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CryptoConversionQuery
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCryptoExchangeItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangeItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CryptoExchangeItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CryptoExchangeItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CryptoExchangeItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCryptoExchangesList(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CryptoExchangesList{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CryptoExchangesList
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CryptoExchangesList
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CryptoExchangesList
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCryptoConversion(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CryptoConversion{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversion
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCryptoConversionQuery(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CryptoConversionQuery{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversionQuery
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCryptoExchangeItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CryptoExchangeItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoExchangeItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCryptoExchangesList(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CryptoExchangesList{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoExchangesList
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesCryptoConversion(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CryptoConversion{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversion
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCryptoConversionQuery(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CryptoConversionQuery{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoConversionQuery
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCryptoExchangeItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CryptoExchangeItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoExchangeItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCryptoExchangesList(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CryptoExchangesList{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CryptoExchangesList
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
