// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

var (
	currenciesConvertRequestFieldFrom      = big.NewInt(1 << 0)
	currenciesConvertRequestFieldTo        = big.NewInt(1 << 1)
	currenciesConvertRequestFieldAmount    = big.NewInt(1 << 2)
	currenciesConvertRequestFieldPrecision = big.NewInt(1 << 3)
)

type CurrenciesConvertRequest struct {
	// The symbol you want to convert from.
	From string `json:"-" url:"-"`
	// The symbol you want to convert to.
	To string `json:"-" url:"-"`
	// The amount to be converted.
	Amount *float64 `json:"-" url:"amount,omitempty"`
	// The decimal precision of the result.
	Precision *int `json:"-" url:"precision,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CurrenciesConvertRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesConvertRequest) SetFrom(from string) {
	c.From = from
	c.require(currenciesConvertRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesConvertRequest) SetTo(to string) {
	c.To = to
	c.require(currenciesConvertRequestFieldTo)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesConvertRequest) SetAmount(amount *float64) {
	c.Amount = amount
	c.require(currenciesConvertRequestFieldAmount)
}

// SetPrecision sets the Precision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesConvertRequest) SetPrecision(precision *int) {
	c.Precision = precision
	c.require(currenciesConvertRequestFieldPrecision)
}

var (
	currenciesGetInsightsRequestFieldCursor = big.NewInt(1 << 0)
	currenciesGetInsightsRequestFieldSize   = big.NewInt(1 << 1)
)

type CurrenciesGetInsightsRequest struct {
	// Cursor for the next page
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// The number of items per page.
	Size *int `json:"-" url:"size,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CurrenciesGetInsightsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetInsightsRequest) SetCursor(cursor *string) {
	c.Cursor = cursor
	c.require(currenciesGetInsightsRequestFieldCursor)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetInsightsRequest) SetSize(size *int) {
	c.Size = size
	c.require(currenciesGetInsightsRequestFieldSize)
}

var (
	currenciesGetQuoteRequestFieldSymbol    = big.NewInt(1 << 0)
	currenciesGetQuoteRequestFieldPrecision = big.NewInt(1 << 1)
)

type CurrenciesGetQuoteRequest struct {
	// The symbol to get the quote for.
	Symbol string `json:"-" url:"symbol"`
	// The decimal precision of the result.
	Precision *int `json:"-" url:"precision,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CurrenciesGetQuoteRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSymbol sets the Symbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetQuoteRequest) SetSymbol(symbol string) {
	c.Symbol = symbol
	c.require(currenciesGetQuoteRequestFieldSymbol)
}

// SetPrecision sets the Precision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetQuoteRequest) SetPrecision(precision *int) {
	c.Precision = precision
	c.require(currenciesGetQuoteRequestFieldPrecision)
}

var (
	currenciesGetQuotesRequestFieldSymbols   = big.NewInt(1 << 0)
	currenciesGetQuotesRequestFieldPrecision = big.NewInt(1 << 1)
)

type CurrenciesGetQuotesRequest struct {
	// Comma separated list of symbols.
	Symbols string `json:"-" url:"symbols"`
	// The decimal precision of the result.
	Precision *int `json:"-" url:"precision,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CurrenciesGetQuotesRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSymbols sets the Symbols field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetQuotesRequest) SetSymbols(symbols string) {
	c.Symbols = symbols
	c.require(currenciesGetQuotesRequestFieldSymbols)
}

// SetPrecision sets the Precision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetQuotesRequest) SetPrecision(precision *int) {
	c.Precision = precision
	c.require(currenciesGetQuotesRequestFieldPrecision)
}

var (
	currenciesGetSymbolsRequestFieldSize    = big.NewInt(1 << 0)
	currenciesGetSymbolsRequestFieldMode    = big.NewInt(1 << 1)
	currenciesGetSymbolsRequestFieldType    = big.NewInt(1 << 2)
	currenciesGetSymbolsRequestFieldCountry = big.NewInt(1 << 3)
	currenciesGetSymbolsRequestFieldCursor  = big.NewInt(1 << 4)
)

type CurrenciesGetSymbolsRequest struct {
	// The number of items per page.
	Size *int `json:"-" url:"size,omitempty"`
	// The mode of the response.
	Mode *string `json:"-" url:"mode,omitempty"`
	// Type of the instrument.
	Type *string `json:"-" url:"type,omitempty"`
	// Country of the instrument.
	Country *string `json:"-" url:"country,omitempty"`
	// Cursor for the next page
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CurrenciesGetSymbolsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetSymbolsRequest) SetSize(size *int) {
	c.Size = size
	c.require(currenciesGetSymbolsRequestFieldSize)
}

// SetMode sets the Mode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetSymbolsRequest) SetMode(mode *string) {
	c.Mode = mode
	c.require(currenciesGetSymbolsRequestFieldMode)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetSymbolsRequest) SetType(type_ *string) {
	c.Type = type_
	c.require(currenciesGetSymbolsRequestFieldType)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetSymbolsRequest) SetCountry(country *string) {
	c.Country = country
	c.require(currenciesGetSymbolsRequestFieldCountry)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrenciesGetSymbolsRequest) SetCursor(cursor *string) {
	c.Cursor = cursor
	c.require(currenciesGetSymbolsRequestFieldCursor)
}

var (
	conversionFieldInfo   = big.NewInt(1 << 0)
	conversionFieldQuery  = big.NewInt(1 << 1)
	conversionFieldResult = big.NewInt(1 << 2)
)

type Conversion struct {
	Info   *ConversionInfo  `json:"info" url:"info"`
	Query  *ConversionQuery `json:"query" url:"query"`
	Result float64          `json:"result" url:"result"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *Conversion) GetInfo() *ConversionInfo {
	if c == nil {
		return nil
	}
	return c.Info
}

func (c *Conversion) GetQuery() *ConversionQuery {
	if c == nil {
		return nil
	}
	return c.Query
}

func (c *Conversion) GetResult() float64 {
	if c == nil {
		return 0
	}
	return c.Result
}

func (c *Conversion) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *Conversion) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetInfo sets the Info field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Conversion) SetInfo(info *ConversionInfo) {
	c.Info = info
	c.require(conversionFieldInfo)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Conversion) SetQuery(query *ConversionQuery) {
	c.Query = query
	c.require(conversionFieldQuery)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Conversion) SetResult(result float64) {
	c.Result = result
	c.require(conversionFieldResult)
}

func (c *Conversion) UnmarshalJSON(data []byte) error {
	type unmarshaler Conversion
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = Conversion(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *Conversion) MarshalJSON() ([]byte, error) {
	type embed Conversion
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *Conversion) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	conversionQueryFieldFrom      = big.NewInt(1 << 0)
	conversionQueryFieldTo        = big.NewInt(1 << 1)
	conversionQueryFieldAmount    = big.NewInt(1 << 2)
	conversionQueryFieldPrecision = big.NewInt(1 << 3)
)

type ConversionQuery struct {
	// The symbol you want to convert from.
	From string `json:"from" url:"from"`
	// The symbol you want to convert to.
	To string `json:"to" url:"to"`
	// The amount to be converted.
	Amount *float64 `json:"amount,omitempty" url:"amount,omitempty"`
	// The decimal precision of the result.
	Precision *int `json:"precision,omitempty" url:"precision,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConversionQuery) GetFrom() string {
	if c == nil {
		return ""
	}
	return c.From
}

func (c *ConversionQuery) GetTo() string {
	if c == nil {
		return ""
	}
	return c.To
}

func (c *ConversionQuery) GetAmount() *float64 {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *ConversionQuery) GetPrecision() *int {
	if c == nil {
		return nil
	}
	return c.Precision
}

func (c *ConversionQuery) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConversionQuery) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversionQuery) SetFrom(from string) {
	c.From = from
	c.require(conversionQueryFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversionQuery) SetTo(to string) {
	c.To = to
	c.require(conversionQueryFieldTo)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversionQuery) SetAmount(amount *float64) {
	c.Amount = amount
	c.require(conversionQueryFieldAmount)
}

// SetPrecision sets the Precision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversionQuery) SetPrecision(precision *int) {
	c.Precision = precision
	c.require(conversionQueryFieldPrecision)
}

func (c *ConversionQuery) UnmarshalJSON(data []byte) error {
	type unmarshaler ConversionQuery
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConversionQuery(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConversionQuery) MarshalJSON() ([]byte, error) {
	type embed ConversionQuery
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConversionQuery) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
