/*
tradewatch.io

Financial market data for Developers

API version: 3.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tradewatch

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CountryObj type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryObj{}

// CountryObj struct for CountryObj
type CountryObj struct {
	// Country symbol
	Symbol string `json:"symbol"`
}

type _CountryObj CountryObj

// NewCountryObj instantiates a new CountryObj object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryObj(symbol string) *CountryObj {
	this := CountryObj{}
	this.Symbol = symbol
	return &this
}

// NewCountryObjWithDefaults instantiates a new CountryObj object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryObjWithDefaults() *CountryObj {
	this := CountryObj{}
	return &this
}

// GetSymbol returns the Symbol field value
func (o *CountryObj) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *CountryObj) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *CountryObj) SetSymbol(v string) {
	o.Symbol = v
}

func (o CountryObj) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryObj) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["symbol"] = o.Symbol
	return toSerialize, nil
}

func (o *CountryObj) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"symbol",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCountryObj := _CountryObj{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCountryObj)

	if err != nil {
		return err
	}

	*o = CountryObj(varCountryObj)

	return err
}

type NullableCountryObj struct {
	value *CountryObj
	isSet bool
}

func (v NullableCountryObj) Get() *CountryObj {
	return v.value
}

func (v *NullableCountryObj) Set(val *CountryObj) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryObj) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryObj) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryObj(val *CountryObj) *NullableCountryObj {
	return &NullableCountryObj{value: val, isSet: true}
}

func (v NullableCountryObj) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryObj) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


