/*
tradewatch.io

Financial market data for Developers

API version: 3.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tradewatch

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiUsageDataTransfer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiUsageDataTransfer{}

// ApiUsageDataTransfer Data transfer
type ApiUsageDataTransfer struct {
	Request int32 `json:"request"`
	Response int32 `json:"response"`
}

type _ApiUsageDataTransfer ApiUsageDataTransfer

// NewApiUsageDataTransfer instantiates a new ApiUsageDataTransfer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiUsageDataTransfer(request int32, response int32) *ApiUsageDataTransfer {
	this := ApiUsageDataTransfer{}
	this.Request = request
	this.Response = response
	return &this
}

// NewApiUsageDataTransferWithDefaults instantiates a new ApiUsageDataTransfer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiUsageDataTransferWithDefaults() *ApiUsageDataTransfer {
	this := ApiUsageDataTransfer{}
	return &this
}

// GetRequest returns the Request field value
func (o *ApiUsageDataTransfer) GetRequest() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Request
}

// GetRequestOk returns a tuple with the Request field value
// and a boolean to check if the value has been set.
func (o *ApiUsageDataTransfer) GetRequestOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Request, true
}

// SetRequest sets field value
func (o *ApiUsageDataTransfer) SetRequest(v int32) {
	o.Request = v
}

// GetResponse returns the Response field value
func (o *ApiUsageDataTransfer) GetResponse() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Response
}

// GetResponseOk returns a tuple with the Response field value
// and a boolean to check if the value has been set.
func (o *ApiUsageDataTransfer) GetResponseOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Response, true
}

// SetResponse sets field value
func (o *ApiUsageDataTransfer) SetResponse(v int32) {
	o.Response = v
}

func (o ApiUsageDataTransfer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiUsageDataTransfer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["request"] = o.Request
	toSerialize["response"] = o.Response
	return toSerialize, nil
}

func (o *ApiUsageDataTransfer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"request",
		"response",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiUsageDataTransfer := _ApiUsageDataTransfer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiUsageDataTransfer)

	if err != nil {
		return err
	}

	*o = ApiUsageDataTransfer(varApiUsageDataTransfer)

	return err
}

type NullableApiUsageDataTransfer struct {
	value *ApiUsageDataTransfer
	isSet bool
}

func (v NullableApiUsageDataTransfer) Get() *ApiUsageDataTransfer {
	return v.value
}

func (v *NullableApiUsageDataTransfer) Set(val *ApiUsageDataTransfer) {
	v.value = val
	v.isSet = true
}

func (v NullableApiUsageDataTransfer) IsSet() bool {
	return v.isSet
}

func (v *NullableApiUsageDataTransfer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiUsageDataTransfer(val *ApiUsageDataTransfer) *NullableApiUsageDataTransfer {
	return &NullableApiUsageDataTransfer{value: val, isSet: true}
}

func (v NullableApiUsageDataTransfer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiUsageDataTransfer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


