/*
tradewatch.io

Financial market data for Developers

API version: 3.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tradewatch

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiUsageEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiUsageEntry{}

// ApiUsageEntry Usage history entry
type ApiUsageEntry struct {
	Requests int32 `json:"requests"`
	Data ApiUsageDataTransfer `json:"data"`
}

type _ApiUsageEntry ApiUsageEntry

// NewApiUsageEntry instantiates a new ApiUsageEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiUsageEntry(requests int32, data ApiUsageDataTransfer) *ApiUsageEntry {
	this := ApiUsageEntry{}
	this.Requests = requests
	this.Data = data
	return &this
}

// NewApiUsageEntryWithDefaults instantiates a new ApiUsageEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiUsageEntryWithDefaults() *ApiUsageEntry {
	this := ApiUsageEntry{}
	return &this
}

// GetRequests returns the Requests field value
func (o *ApiUsageEntry) GetRequests() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value
// and a boolean to check if the value has been set.
func (o *ApiUsageEntry) GetRequestsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Requests, true
}

// SetRequests sets field value
func (o *ApiUsageEntry) SetRequests(v int32) {
	o.Requests = v
}

// GetData returns the Data field value
func (o *ApiUsageEntry) GetData() ApiUsageDataTransfer {
	if o == nil {
		var ret ApiUsageDataTransfer
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApiUsageEntry) GetDataOk() (*ApiUsageDataTransfer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ApiUsageEntry) SetData(v ApiUsageDataTransfer) {
	o.Data = v
}

func (o ApiUsageEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiUsageEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requests"] = o.Requests
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ApiUsageEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requests",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiUsageEntry := _ApiUsageEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiUsageEntry)

	if err != nil {
		return err
	}

	*o = ApiUsageEntry(varApiUsageEntry)

	return err
}

type NullableApiUsageEntry struct {
	value *ApiUsageEntry
	isSet bool
}

func (v NullableApiUsageEntry) Get() *ApiUsageEntry {
	return v.value
}

func (v *NullableApiUsageEntry) Set(val *ApiUsageEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableApiUsageEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableApiUsageEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiUsageEntry(val *ApiUsageEntry) *NullableApiUsageEntry {
	return &NullableApiUsageEntry{value: val, isSet: true}
}

func (v NullableApiUsageEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiUsageEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


