// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

type AccountUsageStatisticsOutput = map[string]interface{}

// Data transfer
var (
	aPIUsageDataTransferFieldRequest  = big.NewInt(1 << 0)
	aPIUsageDataTransferFieldResponse = big.NewInt(1 << 1)
)

type APIUsageDataTransfer struct {
	Request  int `json:"request" url:"request"`
	Response int `json:"response" url:"response"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *APIUsageDataTransfer) GetRequest() int {
	if a == nil {
		return 0
	}
	return a.Request
}

func (a *APIUsageDataTransfer) GetResponse() int {
	if a == nil {
		return 0
	}
	return a.Response
}

func (a *APIUsageDataTransfer) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *APIUsageDataTransfer) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIUsageDataTransfer) SetRequest(request int) {
	a.Request = request
	a.require(aPIUsageDataTransferFieldRequest)
}

// SetResponse sets the Response field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIUsageDataTransfer) SetResponse(response int) {
	a.Response = response
	a.require(aPIUsageDataTransferFieldResponse)
}

func (a *APIUsageDataTransfer) UnmarshalJSON(data []byte) error {
	type unmarshaler APIUsageDataTransfer
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = APIUsageDataTransfer(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *APIUsageDataTransfer) MarshalJSON() ([]byte, error) {
	type embed APIUsageDataTransfer
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *APIUsageDataTransfer) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Usage history entry
var (
	aPIUsageEntryFieldRequests = big.NewInt(1 << 0)
	aPIUsageEntryFieldData     = big.NewInt(1 << 1)
)

type APIUsageEntry struct {
	Requests int                   `json:"requests" url:"requests"`
	Data     *APIUsageDataTransfer `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *APIUsageEntry) GetRequests() int {
	if a == nil {
		return 0
	}
	return a.Requests
}

func (a *APIUsageEntry) GetData() *APIUsageDataTransfer {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *APIUsageEntry) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *APIUsageEntry) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetRequests sets the Requests field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIUsageEntry) SetRequests(requests int) {
	a.Requests = requests
	a.require(aPIUsageEntryFieldRequests)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIUsageEntry) SetData(data *APIUsageDataTransfer) {
	a.Data = data
	a.require(aPIUsageEntryFieldData)
}

func (a *APIUsageEntry) UnmarshalJSON(data []byte) error {
	type unmarshaler APIUsageEntry
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = APIUsageEntry(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *APIUsageEntry) MarshalJSON() ([]byte, error) {
	type embed APIUsageEntry
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *APIUsageEntry) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	conversionInfoFieldTimestamp = big.NewInt(1 << 0)
	conversionInfoFieldRate      = big.NewInt(1 << 1)
)

type ConversionInfo struct {
	Timestamp int     `json:"timestamp" url:"timestamp"`
	Rate      float64 `json:"rate" url:"rate"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConversionInfo) GetTimestamp() int {
	if c == nil {
		return 0
	}
	return c.Timestamp
}

func (c *ConversionInfo) GetRate() float64 {
	if c == nil {
		return 0
	}
	return c.Rate
}

func (c *ConversionInfo) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConversionInfo) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversionInfo) SetTimestamp(timestamp int) {
	c.Timestamp = timestamp
	c.require(conversionInfoFieldTimestamp)
}

// SetRate sets the Rate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConversionInfo) SetRate(rate float64) {
	c.Rate = rate
	c.require(conversionInfoFieldRate)
}

func (c *ConversionInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler ConversionInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConversionInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConversionInfo) MarshalJSON() ([]byte, error) {
	type embed ConversionInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConversionInfo) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cursorPageTCustomizedNewsOutFieldItems                = big.NewInt(1 << 0)
	cursorPageTCustomizedNewsOutFieldTotal                = big.NewInt(1 << 1)
	cursorPageTCustomizedNewsOutFieldCurrentPage          = big.NewInt(1 << 2)
	cursorPageTCustomizedNewsOutFieldCurrentPageBackwards = big.NewInt(1 << 3)
	cursorPageTCustomizedNewsOutFieldPreviousPage         = big.NewInt(1 << 4)
	cursorPageTCustomizedNewsOutFieldNextPage             = big.NewInt(1 << 5)
)

type CursorPageTCustomizedNewsOut struct {
	Items []*NewsOut `json:"items" url:"items"`
	// Total items
	Total *int `json:"total,omitempty" url:"total,omitempty"`
	// Cursor to refetch the current page
	CurrentPage *string `json:"current_page,omitempty" url:"current_page,omitempty"`
	// Cursor to refetch the current page starting from the last item
	CurrentPageBackwards *string `json:"current_page_backwards,omitempty" url:"current_page_backwards,omitempty"`
	// Cursor for the previous page
	PreviousPage *string `json:"previous_page,omitempty" url:"previous_page,omitempty"`
	// Cursor for the next page
	NextPage *string `json:"next_page,omitempty" url:"next_page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CursorPageTCustomizedNewsOut) GetItems() []*NewsOut {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CursorPageTCustomizedNewsOut) GetTotal() *int {
	if c == nil {
		return nil
	}
	return c.Total
}

func (c *CursorPageTCustomizedNewsOut) GetCurrentPage() *string {
	if c == nil {
		return nil
	}
	return c.CurrentPage
}

func (c *CursorPageTCustomizedNewsOut) GetCurrentPageBackwards() *string {
	if c == nil {
		return nil
	}
	return c.CurrentPageBackwards
}

func (c *CursorPageTCustomizedNewsOut) GetPreviousPage() *string {
	if c == nil {
		return nil
	}
	return c.PreviousPage
}

func (c *CursorPageTCustomizedNewsOut) GetNextPage() *string {
	if c == nil {
		return nil
	}
	return c.NextPage
}

func (c *CursorPageTCustomizedNewsOut) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CursorPageTCustomizedNewsOut) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedNewsOut) SetItems(items []*NewsOut) {
	c.Items = items
	c.require(cursorPageTCustomizedNewsOutFieldItems)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedNewsOut) SetTotal(total *int) {
	c.Total = total
	c.require(cursorPageTCustomizedNewsOutFieldTotal)
}

// SetCurrentPage sets the CurrentPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedNewsOut) SetCurrentPage(currentPage *string) {
	c.CurrentPage = currentPage
	c.require(cursorPageTCustomizedNewsOutFieldCurrentPage)
}

// SetCurrentPageBackwards sets the CurrentPageBackwards field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedNewsOut) SetCurrentPageBackwards(currentPageBackwards *string) {
	c.CurrentPageBackwards = currentPageBackwards
	c.require(cursorPageTCustomizedNewsOutFieldCurrentPageBackwards)
}

// SetPreviousPage sets the PreviousPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedNewsOut) SetPreviousPage(previousPage *string) {
	c.PreviousPage = previousPage
	c.require(cursorPageTCustomizedNewsOutFieldPreviousPage)
}

// SetNextPage sets the NextPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedNewsOut) SetNextPage(nextPage *string) {
	c.NextPage = nextPage
	c.require(cursorPageTCustomizedNewsOutFieldNextPage)
}

func (c *CursorPageTCustomizedNewsOut) UnmarshalJSON(data []byte) error {
	type unmarshaler CursorPageTCustomizedNewsOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CursorPageTCustomizedNewsOut(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CursorPageTCustomizedNewsOut) MarshalJSON() ([]byte, error) {
	type embed CursorPageTCustomizedNewsOut
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CursorPageTCustomizedNewsOut) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cursorPageTCustomizedSymbolsOutFullFieldItems                = big.NewInt(1 << 0)
	cursorPageTCustomizedSymbolsOutFullFieldTotal                = big.NewInt(1 << 1)
	cursorPageTCustomizedSymbolsOutFullFieldCurrentPage          = big.NewInt(1 << 2)
	cursorPageTCustomizedSymbolsOutFullFieldCurrentPageBackwards = big.NewInt(1 << 3)
	cursorPageTCustomizedSymbolsOutFullFieldPreviousPage         = big.NewInt(1 << 4)
	cursorPageTCustomizedSymbolsOutFullFieldNextPage             = big.NewInt(1 << 5)
)

type CursorPageTCustomizedSymbolsOutFull struct {
	Items []*SymbolsOutFull `json:"items" url:"items"`
	// Total items
	Total *int `json:"total,omitempty" url:"total,omitempty"`
	// Cursor to refetch the current page
	CurrentPage *string `json:"current_page,omitempty" url:"current_page,omitempty"`
	// Cursor to refetch the current page starting from the last item
	CurrentPageBackwards *string `json:"current_page_backwards,omitempty" url:"current_page_backwards,omitempty"`
	// Cursor for the previous page
	PreviousPage *string `json:"previous_page,omitempty" url:"previous_page,omitempty"`
	// Cursor for the next page
	NextPage *string `json:"next_page,omitempty" url:"next_page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CursorPageTCustomizedSymbolsOutFull) GetItems() []*SymbolsOutFull {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CursorPageTCustomizedSymbolsOutFull) GetTotal() *int {
	if c == nil {
		return nil
	}
	return c.Total
}

func (c *CursorPageTCustomizedSymbolsOutFull) GetCurrentPage() *string {
	if c == nil {
		return nil
	}
	return c.CurrentPage
}

func (c *CursorPageTCustomizedSymbolsOutFull) GetCurrentPageBackwards() *string {
	if c == nil {
		return nil
	}
	return c.CurrentPageBackwards
}

func (c *CursorPageTCustomizedSymbolsOutFull) GetPreviousPage() *string {
	if c == nil {
		return nil
	}
	return c.PreviousPage
}

func (c *CursorPageTCustomizedSymbolsOutFull) GetNextPage() *string {
	if c == nil {
		return nil
	}
	return c.NextPage
}

func (c *CursorPageTCustomizedSymbolsOutFull) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CursorPageTCustomizedSymbolsOutFull) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedSymbolsOutFull) SetItems(items []*SymbolsOutFull) {
	c.Items = items
	c.require(cursorPageTCustomizedSymbolsOutFullFieldItems)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedSymbolsOutFull) SetTotal(total *int) {
	c.Total = total
	c.require(cursorPageTCustomizedSymbolsOutFullFieldTotal)
}

// SetCurrentPage sets the CurrentPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedSymbolsOutFull) SetCurrentPage(currentPage *string) {
	c.CurrentPage = currentPage
	c.require(cursorPageTCustomizedSymbolsOutFullFieldCurrentPage)
}

// SetCurrentPageBackwards sets the CurrentPageBackwards field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedSymbolsOutFull) SetCurrentPageBackwards(currentPageBackwards *string) {
	c.CurrentPageBackwards = currentPageBackwards
	c.require(cursorPageTCustomizedSymbolsOutFullFieldCurrentPageBackwards)
}

// SetPreviousPage sets the PreviousPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedSymbolsOutFull) SetPreviousPage(previousPage *string) {
	c.PreviousPage = previousPage
	c.require(cursorPageTCustomizedSymbolsOutFullFieldPreviousPage)
}

// SetNextPage sets the NextPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CursorPageTCustomizedSymbolsOutFull) SetNextPage(nextPage *string) {
	c.NextPage = nextPage
	c.require(cursorPageTCustomizedSymbolsOutFullFieldNextPage)
}

func (c *CursorPageTCustomizedSymbolsOutFull) UnmarshalJSON(data []byte) error {
	type unmarshaler CursorPageTCustomizedSymbolsOutFull
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CursorPageTCustomizedSymbolsOutFull(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CursorPageTCustomizedSymbolsOutFull) MarshalJSON() ([]byte, error) {
	type embed CursorPageTCustomizedSymbolsOutFull
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CursorPageTCustomizedSymbolsOutFull) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	errorDetailsFieldCode    = big.NewInt(1 << 0)
	errorDetailsFieldMessage = big.NewInt(1 << 1)
)

type ErrorDetails struct {
	Code    int    `json:"code" url:"code"`
	Message string `json:"message" url:"message"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorDetails) GetCode() int {
	if e == nil {
		return 0
	}
	return e.Code
}

func (e *ErrorDetails) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *ErrorDetails) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ErrorDetails) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorDetails) SetCode(code int) {
	e.Code = code
	e.require(errorDetailsFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorDetails) SetMessage(message string) {
	e.Message = message
	e.require(errorDetailsFieldMessage)
}

func (e *ErrorDetails) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorDetails
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorDetails(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorDetails) MarshalJSON() ([]byte, error) {
	type embed ErrorDetails
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ErrorDetails) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	errorResponseBodyFieldError = big.NewInt(1 << 0)
)

type ErrorResponseBody struct {
	Error *ErrorDetails `json:"error" url:"error"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorResponseBody) GetError() *ErrorDetails {
	if e == nil {
		return nil
	}
	return e.Error
}

func (e *ErrorResponseBody) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ErrorResponseBody) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponseBody) SetError(error_ *ErrorDetails) {
	e.Error = error_
	e.require(errorResponseBodyFieldError)
}

func (e *ErrorResponseBody) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorResponseBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorResponseBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorResponseBody) MarshalJSON() ([]byte, error) {
	type embed ErrorResponseBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ErrorResponseBody) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	hTTPValidationErrorFieldDetail = big.NewInt(1 << 0)
)

type HTTPValidationError struct {
	Detail []*ValidationError `json:"detail,omitempty" url:"detail,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (h *HTTPValidationError) GetDetail() []*ValidationError {
	if h == nil {
		return nil
	}
	return h.Detail
}

func (h *HTTPValidationError) GetExtraProperties() map[string]interface{} {
	if h == nil {
		return nil
	}
	return h.extraProperties
}

func (h *HTTPValidationError) require(field *big.Int) {
	if h.explicitFields == nil {
		h.explicitFields = big.NewInt(0)
	}
	h.explicitFields.Or(h.explicitFields, field)
}

// SetDetail sets the Detail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HTTPValidationError) SetDetail(detail []*ValidationError) {
	h.Detail = detail
	h.require(hTTPValidationErrorFieldDetail)
}

func (h *HTTPValidationError) UnmarshalJSON(data []byte) error {
	type unmarshaler HTTPValidationError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*h = HTTPValidationError(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *h)
	if err != nil {
		return err
	}
	h.extraProperties = extraProperties
	h.rawJSON = json.RawMessage(data)
	return nil
}

func (h *HTTPValidationError) MarshalJSON() ([]byte, error) {
	type embed HTTPValidationError
	var marshaler = struct {
		embed
	}{
		embed: embed(*h),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, h.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (h *HTTPValidationError) String() string {
	if h == nil {
		return "<nil>"
	}
	if len(h.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(h.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}

var (
	lastQuoteFieldSymbol    = big.NewInt(1 << 0)
	lastQuoteFieldAsk       = big.NewInt(1 << 1)
	lastQuoteFieldBid       = big.NewInt(1 << 2)
	lastQuoteFieldMid       = big.NewInt(1 << 3)
	lastQuoteFieldTimestamp = big.NewInt(1 << 4)
)

type LastQuote struct {
	// Symbol name
	Symbol string `json:"symbol" url:"symbol"`
	// The ask price.
	Ask float64 `json:"ask" url:"ask"`
	// The bid price.
	Bid float64 `json:"bid" url:"bid"`
	// The mid price.
	Mid       float64 `json:"mid" url:"mid"`
	Timestamp int     `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LastQuote) GetSymbol() string {
	if l == nil {
		return ""
	}
	return l.Symbol
}

func (l *LastQuote) GetAsk() float64 {
	if l == nil {
		return 0
	}
	return l.Ask
}

func (l *LastQuote) GetBid() float64 {
	if l == nil {
		return 0
	}
	return l.Bid
}

func (l *LastQuote) GetMid() float64 {
	if l == nil {
		return 0
	}
	return l.Mid
}

func (l *LastQuote) GetTimestamp() int {
	if l == nil {
		return 0
	}
	return l.Timestamp
}

func (l *LastQuote) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LastQuote) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetSymbol sets the Symbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LastQuote) SetSymbol(symbol string) {
	l.Symbol = symbol
	l.require(lastQuoteFieldSymbol)
}

// SetAsk sets the Ask field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LastQuote) SetAsk(ask float64) {
	l.Ask = ask
	l.require(lastQuoteFieldAsk)
}

// SetBid sets the Bid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LastQuote) SetBid(bid float64) {
	l.Bid = bid
	l.require(lastQuoteFieldBid)
}

// SetMid sets the Mid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LastQuote) SetMid(mid float64) {
	l.Mid = mid
	l.require(lastQuoteFieldMid)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LastQuote) SetTimestamp(timestamp int) {
	l.Timestamp = timestamp
	l.require(lastQuoteFieldTimestamp)
}

func (l *LastQuote) UnmarshalJSON(data []byte) error {
	type unmarshaler LastQuote
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LastQuote(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LastQuote) MarshalJSON() ([]byte, error) {
	type embed LastQuote
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LastQuote) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	lastQuotesFieldItems = big.NewInt(1 << 0)
)

type LastQuotes struct {
	Items []*LastQuote `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LastQuotes) GetItems() []*LastQuote {
	if l == nil {
		return nil
	}
	return l.Items
}

func (l *LastQuotes) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LastQuotes) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LastQuotes) SetItems(items []*LastQuote) {
	l.Items = items
	l.require(lastQuotesFieldItems)
}

func (l *LastQuotes) UnmarshalJSON(data []byte) error {
	type unmarshaler LastQuotes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LastQuotes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LastQuotes) MarshalJSON() ([]byte, error) {
	type embed LastQuotes
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LastQuotes) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	newsMetaDataFieldMarkets  = big.NewInt(1 << 0)
	newsMetaDataFieldTickets  = big.NewInt(1 << 1)
	newsMetaDataFieldHashtags = big.NewInt(1 << 2)
)

type NewsMetaData struct {
	Markets  []string `json:"markets,omitempty" url:"markets,omitempty"`
	Tickets  []string `json:"tickets,omitempty" url:"tickets,omitempty"`
	Hashtags []string `json:"hashtags,omitempty" url:"hashtags,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NewsMetaData) GetMarkets() []string {
	if n == nil {
		return nil
	}
	return n.Markets
}

func (n *NewsMetaData) GetTickets() []string {
	if n == nil {
		return nil
	}
	return n.Tickets
}

func (n *NewsMetaData) GetHashtags() []string {
	if n == nil {
		return nil
	}
	return n.Hashtags
}

func (n *NewsMetaData) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NewsMetaData) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetMarkets sets the Markets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NewsMetaData) SetMarkets(markets []string) {
	n.Markets = markets
	n.require(newsMetaDataFieldMarkets)
}

// SetTickets sets the Tickets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NewsMetaData) SetTickets(tickets []string) {
	n.Tickets = tickets
	n.require(newsMetaDataFieldTickets)
}

// SetHashtags sets the Hashtags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NewsMetaData) SetHashtags(hashtags []string) {
	n.Hashtags = hashtags
	n.require(newsMetaDataFieldHashtags)
}

func (n *NewsMetaData) UnmarshalJSON(data []byte) error {
	type unmarshaler NewsMetaData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NewsMetaData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NewsMetaData) MarshalJSON() ([]byte, error) {
	type embed NewsMetaData
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NewsMetaData) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	newsOutFieldTimestamp = big.NewInt(1 << 0)
	newsOutFieldContent   = big.NewInt(1 << 1)
	newsOutFieldMetaData  = big.NewInt(1 << 2)
)

type NewsOut struct {
	Timestamp int           `json:"timestamp" url:"timestamp"`
	Content   string        `json:"content" url:"content"`
	MetaData  *NewsMetaData `json:"meta_data" url:"meta_data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NewsOut) GetTimestamp() int {
	if n == nil {
		return 0
	}
	return n.Timestamp
}

func (n *NewsOut) GetContent() string {
	if n == nil {
		return ""
	}
	return n.Content
}

func (n *NewsOut) GetMetaData() *NewsMetaData {
	if n == nil {
		return nil
	}
	return n.MetaData
}

func (n *NewsOut) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NewsOut) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NewsOut) SetTimestamp(timestamp int) {
	n.Timestamp = timestamp
	n.require(newsOutFieldTimestamp)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NewsOut) SetContent(content string) {
	n.Content = content
	n.require(newsOutFieldContent)
}

// SetMetaData sets the MetaData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NewsOut) SetMetaData(metaData *NewsMetaData) {
	n.MetaData = metaData
	n.require(newsOutFieldMetaData)
}

func (n *NewsOut) UnmarshalJSON(data []byte) error {
	type unmarshaler NewsOut
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NewsOut(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NewsOut) MarshalJSON() ([]byte, error) {
	type embed NewsOut
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NewsOut) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	symbolsOutFullFieldSymbol = big.NewInt(1 << 0)
	symbolsOutFullFieldName   = big.NewInt(1 << 1)
)

type SymbolsOutFull struct {
	// The unique symbol of the financial instrument (e.g. AAPL, BTCUSD, etc.).
	Symbol string `json:"symbol" url:"symbol"`
	// The full name of the financial instrument.
	Name string `json:"name" url:"name"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SymbolsOutFull) GetSymbol() string {
	if s == nil {
		return ""
	}
	return s.Symbol
}

func (s *SymbolsOutFull) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SymbolsOutFull) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SymbolsOutFull) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSymbol sets the Symbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SymbolsOutFull) SetSymbol(symbol string) {
	s.Symbol = symbol
	s.require(symbolsOutFullFieldSymbol)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SymbolsOutFull) SetName(name string) {
	s.Name = name
	s.require(symbolsOutFullFieldName)
}

func (s *SymbolsOutFull) UnmarshalJSON(data []byte) error {
	type unmarshaler SymbolsOutFull
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SymbolsOutFull(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SymbolsOutFull) MarshalJSON() ([]byte, error) {
	type embed SymbolsOutFull
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SymbolsOutFull) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	validationErrorFieldLoc  = big.NewInt(1 << 0)
	validationErrorFieldMsg  = big.NewInt(1 << 1)
	validationErrorFieldType = big.NewInt(1 << 2)
)

type ValidationError struct {
	Loc  []*ValidationErrorLocItem `json:"loc" url:"loc"`
	Msg  string                    `json:"msg" url:"msg"`
	Type string                    `json:"type" url:"type"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *ValidationError) GetLoc() []*ValidationErrorLocItem {
	if v == nil {
		return nil
	}
	return v.Loc
}

func (v *ValidationError) GetMsg() string {
	if v == nil {
		return ""
	}
	return v.Msg
}

func (v *ValidationError) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *ValidationError) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *ValidationError) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetLoc sets the Loc field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidationError) SetLoc(loc []*ValidationErrorLocItem) {
	v.Loc = loc
	v.require(validationErrorFieldLoc)
}

// SetMsg sets the Msg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidationError) SetMsg(msg string) {
	v.Msg = msg
	v.require(validationErrorFieldMsg)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidationError) SetType(type_ string) {
	v.Type = type_
	v.require(validationErrorFieldType)
}

func (v *ValidationError) UnmarshalJSON(data []byte) error {
	type unmarshaler ValidationError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = ValidationError(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *ValidationError) MarshalJSON() ([]byte, error) {
	type embed ValidationError
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *ValidationError) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type ValidationErrorLocItem struct {
	String  string
	Integer int

	typ string
}

func (v *ValidationErrorLocItem) GetString() string {
	if v == nil {
		return ""
	}
	return v.String
}

func (v *ValidationErrorLocItem) GetInteger() int {
	if v == nil {
		return 0
	}
	return v.Integer
}

func (v *ValidationErrorLocItem) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		v.typ = "String"
		v.String = valueString
		return nil
	}
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		v.typ = "Integer"
		v.Integer = valueInteger
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, v)
}

func (v ValidationErrorLocItem) MarshalJSON() ([]byte, error) {
	if v.typ == "String" || v.String != "" {
		return json.Marshal(v.String)
	}
	if v.typ == "Integer" || v.Integer != 0 {
		return json.Marshal(v.Integer)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", v)
}

type ValidationErrorLocItemVisitor interface {
	VisitString(string) error
	VisitInteger(int) error
}

func (v *ValidationErrorLocItem) Accept(visitor ValidationErrorLocItemVisitor) error {
	if v.typ == "String" || v.String != "" {
		return visitor.VisitString(v.String)
	}
	if v.typ == "Integer" || v.Integer != 0 {
		return visitor.VisitInteger(v.Integer)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", v)
}
