// Code generated by Fern. DO NOT EDIT.

package stocks_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	sdk "sdk"
	client "sdk/client"
	option "sdk/option"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestStocksGetQuotesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetQuotesRequest{
		Symbols: "symbols",
	}
	_, invocationErr := client.Stocks.GetQuotes(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetQuotesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetQuotesWithWireMock", "GET", "/stocks/quotes", map[string]string{"symbols": "symbols"}, 1)
}

func TestStocksGetQuoteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetQuoteRequest{
		Symbol: "symbol",
	}
	_, invocationErr := client.Stocks.GetQuote(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetQuoteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetQuoteWithWireMock", "GET", "/stocks/quote", map[string]string{"symbol": "symbol"}, 1)
}

func TestStocksGetSymbolsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetSymbolsRequest{}
	_, invocationErr := client.Stocks.GetSymbols(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetSymbolsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetSymbolsWithWireMock", "GET", "/stocks/symbols", nil, 1)
}

func TestStocksGetInsightsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetInsightsRequest{}
	_, invocationErr := client.Stocks.GetInsights(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetInsightsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetInsightsWithWireMock", "GET", "/stocks/insights", nil, 1)
}

func TestStocksStockGetCountriesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Stocks.StockGetCountries(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksStockGetCountriesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksStockGetCountriesWithWireMock", "GET", "/stocks/countries", nil, 1)
}

func TestStocksGetMarketsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetMarketsRequest{
		Mic: sdk.String(
			"XNYS",
		),
	}
	_, invocationErr := client.Stocks.GetMarkets(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetMarketsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetMarketsWithWireMock", "GET", "/stocks/markets", map[string]string{"mic": "XNYS"}, 1)
}

func TestStocksGetMarketStatusWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetMarketStatusRequest{
		Mic: sdk.String(
			"XNYS",
		),
	}
	_, invocationErr := client.Stocks.GetMarketStatus(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetMarketStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetMarketStatusWithWireMock", "GET", "/stocks/markets/status", map[string]string{"mic": "XNYS"}, 1)
}

func TestStocksGetTradingHoursWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetTradingHoursRequest{
		Mic: sdk.String(
			"XNAS",
		),
		Start: sdk.MustParseDate(
			"2025-01-01",
		),
		End: sdk.MustParseDate(
			"2025-01-31",
		),
	}
	_, invocationErr := client.Stocks.GetTradingHours(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetTradingHoursWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetTradingHoursWithWireMock", "GET", "/stocks/markets/hours", map[string]string{"mic": "XNAS", "start": "2025-01-01", "end": "2025-01-31"}, 1)
}

func TestStocksGetMarketHolidaysWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetMarketHolidaysRequest{
		Mic: sdk.String(
			"XNYS",
		),
		Start: sdk.MustParseDate(
			"2026-02-17",
		),
		End: sdk.MustParseDate(
			"2026-02-24",
		),
	}
	_, invocationErr := client.Stocks.GetMarketHolidays(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetMarketHolidaysWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetMarketHolidaysWithWireMock", "GET", "/stocks/markets/holidays", map[string]string{"mic": "XNYS", "start": "2026-02-17", "end": "2026-02-24"}, 1)
}

func TestStocksGetStockDataWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetStockDataRequest{
		Symbol: "AAPL",
	}
	_, invocationErr := client.Stocks.GetStockData(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetStockDataWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetStockDataWithWireMock", "GET", "/stocks/AAPL", nil, 1)
}

func TestStocksGetHistoricalOhlcWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetHistoricalOhlcRequest{
		Symbol:     "symbol",
		Resolution: sdk.HistoricalDataResolutionValue5,
		Start:      1,
		End:        1,
	}
	_, invocationErr := client.Stocks.GetHistoricalOhlc(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetHistoricalOhlcWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetHistoricalOhlcWithWireMock", "GET", "/stocks/symbol/ohlc", map[string]string{"resolution": "5", "start": "1", "end": "1"}, 1)
}

func TestStocksGetHistoricalTicksWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.StocksGetHistoricalTicksRequest{
		Symbol: "symbol",
		Start:  1,
		End:    1,
	}
	_, invocationErr := client.Stocks.GetHistoricalTicks(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStocksGetHistoricalTicksWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStocksGetHistoricalTicksWithWireMock", "GET", "/stocks/symbol/ticks", map[string]string{"start": "1", "end": "1"}, 1)
}
