// Code generated by Fern. DO NOT EDIT.

package stocks

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get the last quote tick for the provided symbols.
func (c *Client) GetQuotes(
	ctx context.Context,
	request *sdk.StocksGetQuotesRequest,
	opts ...option.RequestOption,
) (*sdk.LastQuotes, error) {
	response, err := c.WithRawResponse.GetQuotes(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the last quote tick for the provided symbol.
func (c *Client) GetQuote(
	ctx context.Context,
	request *sdk.StocksGetQuoteRequest,
	opts ...option.RequestOption,
) (*sdk.LastQuote, error) {
	response, err := c.WithRawResponse.GetQuote(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get list of available symbols
func (c *Client) GetSymbols(
	ctx context.Context,
	request *sdk.StocksGetSymbolsRequest,
	opts ...option.RequestOption,
) (*sdk.CursorPageTCustomizedSymbolsOutFullStocks, error) {
	response, err := c.WithRawResponse.GetSymbols(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get recent stocks insights.
func (c *Client) GetInsights(
	ctx context.Context,
	request *sdk.StocksGetInsightsRequest,
	opts ...option.RequestOption,
) (*sdk.CursorPageTCustomizedNewsOut, error) {
	response, err := c.WithRawResponse.GetInsights(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get list of available countries
func (c *Client) StockGetCountries(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.CountriesList, error) {
	response, err := c.WithRawResponse.StockGetCountries(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get details about the markets available in this API.
func (c *Client) GetMarkets(
	ctx context.Context,
	request *sdk.StocksGetMarketsRequest,
	opts ...option.RequestOption,
) ([]*sdk.MarketResponse, error) {
	response, err := c.WithRawResponse.GetMarkets(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the current status (open or closed) of a market. It takes holidays and half-days into account but does not factor in circuit breakers or halts.
func (c *Client) GetMarketStatus(
	ctx context.Context,
	request *sdk.StocksGetMarketStatusRequest,
	opts ...option.RequestOption,
) ([]*sdk.MarketStatusResponse, error) {
	response, err := c.WithRawResponse.GetMarketStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get trading hours. It takes half-days into account.
func (c *Client) GetTradingHours(
	ctx context.Context,
	request *sdk.StocksGetTradingHoursRequest,
	opts ...option.RequestOption,
) ([]*sdk.TradingHoursResponse, error) {
	response, err := c.WithRawResponse.GetTradingHours(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get market holidays. It takes half-days into account.
func (c *Client) GetMarketHolidays(
	ctx context.Context,
	request *sdk.StocksGetMarketHolidaysRequest,
	opts ...option.RequestOption,
) ([]*sdk.MarketHolidayResponse, error) {
	response, err := c.WithRawResponse.GetMarketHolidays(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetStockData(
	ctx context.Context,
	request *sdk.StocksGetStockDataRequest,
	opts ...option.RequestOption,
) (*sdk.StockDataFlatResponse, error) {
	response, err := c.WithRawResponse.GetStockData(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get historical OHLC candles for a symbol in a selected resolution and time range.
func (c *Client) GetHistoricalOhlc(
	ctx context.Context,
	request *sdk.StocksGetHistoricalOhlcRequest,
	opts ...option.RequestOption,
) (*sdk.HistoricalOhlcResponse, error) {
	response, err := c.WithRawResponse.GetHistoricalOhlc(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get raw historical ticks for a symbol in a selected time range using cursor pagination.
func (c *Client) GetHistoricalTicks(
	ctx context.Context,
	request *sdk.StocksGetHistoricalTicksRequest,
	opts ...option.RequestOption,
) (*sdk.CursorPageTCustomizedHistoricalRawTick, error) {
	response, err := c.WithRawResponse.GetHistoricalTicks(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
