// Code generated by Fern. DO NOT EDIT.

package account

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get the usage statistics of your API account
func (c *Client) GetUsage(
	ctx context.Context,
	request *sdk.AccountGetUsageRequest,
	opts ...option.RequestOption,
) (sdk.AccountUsageStatisticsInput, error) {
	response, err := c.WithRawResponse.GetUsage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
