// Code generated by Fern. DO NOT EDIT.

package commodities

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get the last quote tick for the provided symbols.
func (c *Client) GetQuotes(
	ctx context.Context,
	request *sdk.CommoditiesGetQuotesRequest,
	opts ...option.RequestOption,
) (*sdk.LastQuotes, error) {
	response, err := c.WithRawResponse.GetQuotes(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the last quote tick for the provided symbol.
func (c *Client) GetQuote(
	ctx context.Context,
	request *sdk.CommoditiesGetQuoteRequest,
	opts ...option.RequestOption,
) (*sdk.LastQuote, error) {
	response, err := c.WithRawResponse.GetQuote(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get list of available symbols
func (c *Client) GetSymbols(
	ctx context.Context,
	request *sdk.CommoditiesGetSymbolsRequest,
	opts ...option.RequestOption,
) (*sdk.CursorPageTCustomizedSymbolsOutFull, error) {
	response, err := c.WithRawResponse.GetSymbols(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get recent commodities insights.
func (c *Client) GetInsights(
	ctx context.Context,
	request *sdk.CommoditiesGetInsightsRequest,
	opts ...option.RequestOption,
) (*sdk.CursorPageTCustomizedNewsOut, error) {
	response, err := c.WithRawResponse.GetInsights(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get list of available commodity types
func (c *Client) GetTypes(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.CommodityTypesList, error) {
	response, err := c.WithRawResponse.GetTypes(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
